POST http://127.0.0.1:8000/movies_by_cat
Content-Type: application/json

{
  "categories": [
    "documentary"
  ]
}

###
POST http://127.0.0.1:8000/movies_by_cat
Content-Type: application/json

{
  "categories": [
    "comedy",
    "action"
  ]
}

###
# Test your FastAPI endpoints

GET http://127.0.0.1:8000/all_movies
Accept: application/json

###

